//
//  ZikApi.h
//  Zik Controller
//
//  Created by Rui Araújo on 14/09/14.
//  Copyright (c) 2014 Rui Araújo. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const BATTERY_GET;
FOUNDATION_EXPORT NSString *const VERSION_GET;
FOUNDATION_EXPORT NSString *const CONCERT_HALL_ANGLE_GET;
FOUNDATION_EXPORT NSString *const CONCERT_HALL_ANGLE_SET;
FOUNDATION_EXPORT NSString *const CONCERT_HALL_ENABLED_GET;
FOUNDATION_EXPORT NSString *const CONCERT_HALL_ENABLED_SET;
FOUNDATION_EXPORT NSString *const CONCERT_HALL_GET;
FOUNDATION_EXPORT NSString *const CONCERT_HALL_ROOM_GET;
FOUNDATION_EXPORT NSString *const CONCERT_HALL_ROOM_SET;
FOUNDATION_EXPORT NSString *const EQUALIZER_ENABLED_GET;
FOUNDATION_EXPORT NSString *const EQUALIZER_ENABLED_SET;
FOUNDATION_EXPORT NSString *const EQUALIZER_GET;
FOUNDATION_EXPORT NSString *const EQUALIZER_PRESETS_LIST_GET;
FOUNDATION_EXPORT NSString *const EQUALIZER_PRESET_ID_GET;
FOUNDATION_EXPORT NSString *const EQUALIZER_PRESET_ID_SET;
FOUNDATION_EXPORT NSString *const EQUALIZER_PRESET_VALUE_GET;
FOUNDATION_EXPORT NSString *const EQUALIZER_PRESET_VALUE_SET;
FOUNDATION_EXPORT NSString *const FRIENDLY_NAME_GET;
FOUNDATION_EXPORT NSString *const FRIENDLY_NAME_SET;
FOUNDATION_EXPORT NSString *const NOISE_CANCELLATION_ENABLED_GET;
FOUNDATION_EXPORT NSString *const NOISE_CANCELLATION_ENABLED_SET;
FOUNDATION_EXPORT NSString *const SOUND_EFFECT_ENABLED_GET;
FOUNDATION_EXPORT NSString *const SOUND_EFFECT_ENABLED_SET;
FOUNDATION_EXPORT NSString *const SYSTEM_ANC_PHONE_MODE_GET;
FOUNDATION_EXPORT NSString *const SYSTEM_ANC_PHONE_MODE_SET;
FOUNDATION_EXPORT NSString *const SYSTEM_AUTO_CONNECTION_GET;
FOUNDATION_EXPORT NSString *const SYSTEM_AUTO_CONNECTION_SET;
FOUNDATION_EXPORT NSString *const SYSTEM_AUTO_POWER_OFF_GET;
FOUNDATION_EXPORT NSString *const SYSTEM_AUTO_POWER_OFF_SET;
FOUNDATION_EXPORT NSString *const SYSTEM_AUTO_POWER_OFF_LIST_GET;
FOUNDATION_EXPORT NSString *const SYSTEM_HEAD_DETECTION_ENABLED_GET;
FOUNDATION_EXPORT NSString *const SYSTEM_HEAD_DETECTION_ENABLED_SET;